In [1]:
import numpy as np

In [2]:
x = 2
y = 0
z = 3
gamma1 = 1
gamma2 = 1


l1 = 2
l2 = 2.5
l3 = 2.8

In [3]:
def IK2DOF(x,y,gamma,l1,l2):
    if ((l2-l1) <= np.sqrt(x**2+y**2) and (l2+l1) >= np.sqrt(x**2+y**2)):
        c2 = (x**2+y**2-l1**2-l2**2)/(2*l1*l2)
    else:
        return -1
    s2 = gamma*np.sqrt(1-c2**2)

    q1 = np.arctan2(y,x) - np.arctan2(l2*s2 ,l1 + l2*c2)
    q2 = np.arctan2(s2, c2)

    return q1, q2

In [4]:
np.sqrt(x**2+y**2)

2.0

In [5]:
q1 = np.arctan2(y/gamma1,x/gamma1)

In [6]:
q1

0.0

In [7]:
q1 = np.arctan2(y/gamma1,x/gamma1)

r = gamma1 * np.sqrt(x**2+y**2)

q2, q3 = IK2DOF(r,
                z - l1,
                gamma2,
                l2,
                l3)

In [8]:
r

2.0

In [9]:
print(q1,q2,q3)

0.0 -0.7972106327886452 2.2774412099183414


In [142]:
import roboticstoolbox as rtb

In [11]:
import numpy as np

In [12]:
import matplotlib.pyplot as plt


In [134]:
pi =np.pi

In [221]:
%matplotlib tk
robot = rtb.DHRobot([
            rtb.RevoluteMDH(a=0, alpha = 0, d=0.2),  #F1
            rtb.RevoluteMDH(a=0, alpha=-np.pi/2, d=-0.12 ,offset=-np.pi/2),
            rtb.RevoluteMDH(a=0.25,d=0.1), #F3
            
        ], name="robot")
robot.tool = SE3.Trans(0.28, 0.0, 0.0) * SE3.RPY(pi/2, 0, pi/2)
robot.plot([0,0,0])


PyPlot3D backend, t = 0.05, scene:
  robot: Text(0.0, 0.0, 'robot')

In [168]:
q = np.array([0, 0, 0])

In [169]:
T = robot.fkine(q)
print(T)

   1         0         0         0         
   0         1         0        -0.02      
   0         0         1         0.73      
   0         0         0         1         



In [17]:
from spatialmath import SE3

In [228]:
theta1 = np.random.uniform(0,2*np.pi,1)[0]
theta2 = np.random.uniform(0,2*np.pi,1)[0]
r = np.random.uniform(0.3,0.53,1)[0]
x = r*np.sin(theta1)*np.cos(theta2)
y = r*np.sin(theta1)*np.sin(theta2)
z = r*np.cos(theta1)

In [229]:
target_position = SE3.Trans(x,y,z)
T = SE3(target_position)
solution = robot.ikine_LM(T, mask=[1, 1, 1, 0, 0, 0])
solution.success

True

In [320]:
while(1):
    theta1 = np.random.uniform(0, np.pi)
    theta2 = np.random.uniform(0, 2 * np.pi)
    r = np.random.uniform(0.3, 0.53)
    x = r * np.sin(theta1) * np.cos(theta2)
    y = r * np.sin(theta1) * np.sin(theta2)
    z = r * np.cos(theta1)

    target_position = SE3.Trans(x,y,z)
    T = SE3(target_position)

    solution = robot.ikine_LM(T, mask=[1, 1, 1, 0, 0, 0],tol=0.1)
    print(" p")
    if not solution.success:
        break

solution.success



 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 p
 

KeyboardInterrupt: 

In [306]:
r

0.5197616231654532

In [317]:
np.sqrt(x**2 + y**2 + z**2)

0.5281466055308887

In [315]:
while True:
    theta1 = np.random.uniform(0, np.pi)
    theta2 = np.random.uniform(0, 2 * np.pi)
    r = np.random.uniform(0.3, 0.53)
    x = r * np.sin(theta1) * np.cos(theta2)
    y = r * np.sin(theta1) * np.sin(theta2)
    z = r * np.cos(theta1)

    target_position = SE3.Trans(x, y, z)
    T = SE3(target_position)

    solution = robot.ikine_LM(T, mask=[1, 1, 1, 0, 0, 0], tol=0.01)
    distance = np.sqrt(x**2 + y**2 + z**2)
    if distance > 0.53:
        print(distance)
        print(x, y, z)
        print(theta1, theta2)
        break


KeyboardInterrupt: 

In [294]:
T

   1         0         0         0.1966    
   0         1         0        -0.03433   
   0         0         1        -0.3018    
   0         0         0         1         


In [213]:
robot.fkine(solution.q)

   0.3871   -0.8697    0.3064    0.2002    
  -0.6819   -0.4937   -0.5398   -0.3122    
   0.6207    0        -0.7841   -0.174     
   0         0         0         1         


In [214]:
T

   1         0         0         0.2333    
   0         1         0        -0.3648    
   0         0         1        -0.2335    
   0         0         0         1         


In [181]:
robot.workspace

AttributeError: 'DHRobot' object has no attribute 'workspace'

In [175]:
solution

IKSolution(q=array([-2.49809092, -0.78018969, -2.48980409]), success=True, iterations=6, searches=1, residual=1.1931922774266756e-08, reason='Success')

In [126]:
np.round(solution.q, decimals=2)

array([-0.26, -2.62, -3.82,  1.28])

In [127]:
solution.q

array([-0.25816725, -2.61627494, -3.81822647,  1.27836607])

In [25]:
q

array([0, 0, 0, 0, 0])

In [216]:
robot.plot(solution.q)

PyPlot3D backend, t = 0.05, scene:
  robot: Text(0.0, 0.0, 'robot')